<?php
include_once "../abstrack/Dongvat.php";
include_once "../interface/An.php";
include_once "../interface/Keu.php";
include_once "../interface/sinhsan.php";
class Ga extends Dongvat implements An,Keu,sinhsan{
    public function toinayangi()
    {
        // TODO: Implement toinayangi() method.
        echo "<br> Tối nay ăn thóc ";
    }
    public  function keunhuthenao()
    {
        // TODO: Implement keunhuthenao() method.
        echo "<br> Kêu như gà";
    }
    public function Sinhsanrasao()
    {
        // TODO: Implement Sinhsanrasao() method.
        echo "<br> sinh theo tháng";
    }
    public function Khainien()
    {
        parent::Khainien(); // TODO: Change the autogenerated stub

    }
    public function Tenloai()
    {
        // TODO: Implement Tenloai() method.
        echo "<br> Tôi Tên là gà haroso";
    }
    public function Thongtin()
    {
        // TODO: Implement Thongtin() method.
        echo "<br> Tôi đến từ Vietnamesse";
    }
}