<?php
include_once "../abstrack/Dongvat.php";
include_once "../interface/An.php";
include_once "../interface/Keu.php";
include_once "../interface/sinhsan.php";
class meo extends Dongvat implements An,Keu,sinhsan{
    public function toinayangi()
    {
        // TODO: Implement toinayangi() method.
        echo "<br> Tối nay ăn cá ";
    }
    public  function keunhuthenao()
    {
        // TODO: Implement keunhuthenao() method.
        echo "<br> Kêu như mèo";
    }
    public function Sinhsanrasao()
    {
        // TODO: Implement Sinhsanrasao() method.
        echo "<br> sinh theo năm nhé ";
    }
    public function Khainien()
    {
        parent::Khainien(); // TODO: Change the autogenerated stub

    }
    public function Tenloai()
    {
        // TODO: Implement Tenloai() method.
        echo "<br> Tôi Tên là mèo hari";
    }
    public function Thongtin()
    {
        // TODO: Implement Thongtin() method.
        echo "<br> Tôi đến từ Châu mĩ";
    }
}